/**
 * App name to package name mapping for supported applications.
 * Ported from Open-AutoGLM
 */

const APP_PACKAGES = {
  // Social & Messaging
  "微信": "com.tencent.mm",
  "QQ": "com.tencent.mobileqq",
  "微博": "com.sina.weibo",
  "WeChat": "com.tencent.mm",
  "wechat": "com.tencent.mm",
  "Whatsapp": "com.whatsapp",
  "WhatsApp": "com.whatsapp",
  "Telegram": "org.telegram.messenger",
  "Twitter": "com.twitter.android",
  "twitter": "com.twitter.android",
  "X": "com.twitter.android",
  "飞书": "com.ss.android.lark",
  "QQ邮箱": "com.tencent.androidqqmail",
  "Contacts": "com.android.contacts",
  "contacts": "com.android.contacts",
  "SimpleSMSMessenger": "com.simplemobiletools.smsmessenger",
  "gmail": "com.google.android.gm",
  "Gmail": "com.google.android.gm",
  "GoogleMail": "com.google.android.gm",
  "Google Mail": "com.google.android.gm",
  "GoogleChat": "com.google.android.apps.dynamite",
  "Google Chat": "com.google.android.apps.dynamite",
  "Google-Chat": "com.google.android.apps.dynamite",
  "GoogleContacts": "com.google.android.contacts",
  "Google-Contacts": "com.google.android.contacts",
  "Google Contacts": "com.google.android.contacts",
  "google-contacts": "com.google.android.contacts",
  "google contacts": "com.google.android.contacts",

  // E-commerce
  "淘宝": "com.taobao.taobao",
  "京东": "com.jingdong.app.mall",
  "拼多多": "com.xunmeng.pinduoduo",
  "淘宝闪购": "com.taobao.taobao",
  "京东秒送": "com.jingdong.app.mall",
  "temu": "com.einnovation.temu",
  "Temu": "com.einnovation.temu",

  // Lifestyle & Social
  "小红书": "com.xingin.xhs",
  "豆瓣": "com.douban.frodo",
  "知乎": "com.zhihu.android",
  "Quora": "com.quora.android",
  "quora": "com.quora.android",
  "Reddit": "com.reddit.frontpage",
  "reddit": "com.reddit.frontpage",

  // Maps & Navigation
  "高德地图": "com.autonavi.minimap",
  "百度地图": "com.baidu.BaiduMap",
  "GoogleMaps": "com.google.android.apps.maps",
  "Google Maps": "com.google.android.apps.maps",
  "googlemaps": "com.google.android.apps.maps",
  "google maps": "com.google.android.apps.maps",
  "Osmand": "net.osmand",
  "osmand": "net.osmand",

  // Food & Services
  "美团": "com.sankuai.meituan",
  "大众点评": "com.dianping.v1",
  "饿了么": "me.ele",
  "肯德基": "com.yek.android.kfc.activitys",
  "McDonald": "com.mcdonalds.app",
  "mcdonald": "com.mcdonalds.app",

  // Travel
  "携程": "ctrip.android.view",
  "铁路12306": "com.MobileTicket",
  "12306": "com.MobileTicket",
  "去哪儿": "com.Qunar",
  "去哪儿旅行": "com.Qunar",
  "滴滴出行": "com.sdu.did.psnger",
  "Booking.com": "com.booking",
  "Booking": "com.booking",
  "booking.com": "com.booking",
  "booking": "com.booking",
  "BOOKING.COM": "com.booking",
  "Expedia": "com.expedia.bookings",
  "expedia": "com.expedia.bookings",

  // Video & Entertainment
  "bilibili": "tv.danmaku.bili",
  "抖音": "com.ss.android.ugc.aweme",
  "快手": "com.smile.gifmaker",
  "腾讯视频": "com.tencent.qqlive",
  "爱奇艺": "com.qiyi.video",
  "优酷视频": "com.youku.phone",
  "芒果TV": "com.hunantv.imgo.activity",
  "红果短剧": "com.phoenix.read",
  "Tiktok": "com.zhiliaoapp.musically",
  "tiktok": "com.zhiliaoapp.musically",
  "VLC": "org.videolan.vlc",

  // Music & Audio
  "网易云音乐": "com.netease.cloudmusic",
  "QQ音乐": "com.tencent.qqmusic",
  "汽水音乐": "com.luna.music",
  "喜马拉雅": "com.ximalaya.ting.android",
  "PiMusicPlayer": "com.Project100Pi.themusicplayer",
  "pimusicplayer": "com.Project100Pi.themusicplayer",
  "RetroMusic": "code.name.monkey.retromusic",
  "retromusic": "code.name.monkey.retromusic",
  "AudioRecorder": "com.android.soundrecorder",
  "audiorecorder": "com.android.soundrecorder",

  // Reading
  "番茄小说": "com.dragon.read",
  "番茄免费小说": "com.dragon.read",
  "七猫免费小说": "com.kmxs.reader",
  "Google Play Books": "com.google.android.apps.books",
  "Google-Play-Books": "com.google.android.apps.books",
  "google play books": "com.google.android.apps.books",
  "google-play-books": "com.google.android.apps.books",
  "GooglePlayBooks": "com.google.android.apps.books",
  "googleplaybooks": "com.google.android.apps.books",

  // AI & Tools
  "豆包": "com.larus.nova",
  "Joplin": "net.cozic.joplin",
  "joplin": "net.cozic.joplin",
  "Duolingo": "com.duolingo",
  "duolingo": "com.duolingo",

  // Health & Fitness
  "keep": "com.gotokeep.keep",
  "美柚": "com.lingan.seeyou",
  "GoogleFit": "com.google.android.apps.fitness",
  "googlefit": "com.google.android.apps.fitness",

  // News & Information
  "腾讯新闻": "com.tencent.news",
  "今日头条": "com.ss.android.article.news",

  // Real Estate
  "贝壳找房": "com.lianjia.beike",
  "安居客": "com.anjuke.android.app",

  // Finance
  "同花顺": "com.hexin.plat.android",
  "Bluecoins": "com.rammigsoftware.bluecoins",
  "bluecoins": "com.rammigsoftware.bluecoins",
  "Broccoli": "com.flauschcode.broccoli",
  "broccoli": "com.flauschcode.broccoli",

  // Games
  "星穹铁道": "com.miHoYo.hkrpg",
  "崩坏：星穹铁道": "com.miHoYo.hkrpg",
  "恋与深空": "com.papegames.lysk.cn",

  // System & Google Apps
  "设置": "com.android.settings",
  "AndroidSystemSettings": "com.android.settings",
  "Android System Settings": "com.android.settings",
  "Android  System Settings": "com.android.settings",
  "Android-System-Settings": "com.android.settings",
  "Settings": "com.android.settings",
  "相机": "com.android.camera",
  "相册": "com.android.gallery3d",
  "Chrome": "com.android.chrome",
  "chrome": "com.android.chrome",
  "Google Chrome": "com.android.chrome",
  "Clock": "com.android.deskclock",
  "clock": "com.android.deskclock",
  "Files": "com.android.fileexplorer",
  "files": "com.android.fileexplorer",
  "File Manager": "com.android.fileexplorer",
  "file manager": "com.android.fileexplorer",
  "GoogleFiles": "com.google.android.apps.nbu.files",
  "googlefiles": "com.google.android.apps.nbu.files",
  "FilesbyGoogle": "com.google.android.apps.nbu.files",
  "GoogleCalendar": "com.google.android.calendar",
  "Google-Calendar": "com.google.android.calendar",
  "Google Calendar": "com.google.android.calendar",
  "google-calendar": "com.google.android.calendar",
  "google calendar": "com.google.android.calendar",
  "GoogleClock": "com.google.android.deskclock",
  "Google Clock": "com.google.android.deskclock",
  "Google-Clock": "com.google.android.deskclock",
  "GoogleDocs": "com.google.android.apps.docs.editors.docs",
  "Google Docs": "com.google.android.apps.docs.editors.docs",
  "googledocs": "com.google.android.apps.docs.editors.docs",
  "google docs": "com.google.android.apps.docs.editors.docs",
  "Google Drive": "com.google.android.apps.docs",
  "Google-Drive": "com.google.android.apps.docs",
  "google drive": "com.google.android.apps.docs",
  "google-drive": "com.google.android.apps.docs",
  "GoogleDrive": "com.google.android.apps.docs",
  "Googledrive": "com.google.android.apps.docs",
  "googledrive": "com.google.android.apps.docs",
  "GoogleKeep": "com.google.android.keep",
  "googlekeep": "com.google.android.keep",
  "GooglePlayStore": "com.android.vending",
  "Google Play Store": "com.android.vending",
  "Google-Play-Store": "com.android.vending",
  "GoogleSlides": "com.google.android.apps.docs.editors.slides",
  "Google Slides": "com.google.android.apps.docs.editors.slides",
  "Google-Slides": "com.google.android.apps.docs.editors.slides",
  "GoogleTasks": "com.google.android.apps.tasks",
  "Google Tasks": "com.google.android.apps.tasks",
  "Google-Tasks": "com.google.android.apps.tasks",
  "SimpleCalendarPro": "com.scientificcalculatorplus.simplecalculator.basiccalculator.mathcalc",
};

export default APP_PACKAGES;
